const Products = [
  {
    id: 0,
    idCategory: 0,
    name: 'Coca-Cola',
    description: 'Coca-Cola lata 350ml',
    price: 3.8,
    image: 'path',
  },
  {
    id: 1,
    idCategory: 0,
    name: 'Del Valle Uva',
    description: 'Del Valle sabor uva 290ml',
    price: 2.9,
    image: 'path',
  },
  {
    id: 2,
    idCategory: 0,
    name: 'Del Valle Maracuja',
    description: 'Del Valle sabor Maracuja 290ml',
    price: 2.9,
    image: 'path',
  },
  {
    id: 3,
    idCategory: 0,
    name: 'Red Bull Energy Drink',
    description: 'Red Bull Energy Drink 250 Ml',
    price: 8.0,
    image: 'path',
  },
  {
    id: 4,
    idCategory: 0,
    name: 'Red Bull Sugar Free',
    description: 'Red Bull Sugar Free 250ml',
    price: 11.99,
    image: 'path',
  },
  {
    id: 5,
    idCategory: 0,
    name: 'Red Bull The Tropical Edition',
    description: 'Red Bull The Tropical Edition Sabor Frutas Tropicais 250Ml',
    price: 10.5,
    image: 'path',
  },
  {
    id: 6,
    idCategory: 0,
    name: 'Red Bull The Summer Edition',
    description: 'Red Bull The Summer Edition Sabor Açaí 250Ml',
    price: 10.5,
    image: 'path',
  },
  {
    id: 7,
    idCategory: 0,
    name: 'Monster Energy',
    description: 'Monster Energy Lata 473ml',
    price: 9.99,
    image: 'path',
  },
  {
    id: 8,
    idCategory: 0,
    name: 'Monster Absolutely Zero',
    description: 'Monster Absolutely Zero Lata 473Ml',
    price: 8.15,
    image: 'path',
  },
  {
    id: 9,
    idCategory: 0,
    name: 'Monster Khaos',
    description: 'Monster Khaos Lata 473ml',
    price: 9.5,
    image: 'path',
  },
  {
    id: 10,
    idCategory: 0,
    name: 'Monster Juice Mango Loco',
    description: 'Monster Juice Mango Loco Lata 473Ml',
    price: 9.5,
    image: 'path',
  },
  {
    id: 11,
    idCategory: 0,
    name: 'Monster Energy Ultra Violet',
    description: 'Monster Energy Ultra Violet Lata 473Ml',
    price: 8.15,
    image: 'path',
  },
  {
    id: 12,
    idCategory: 0,
    name: 'Monster Lo-carb',
    description: 'Monster Lo-carb Lata 473ml',
    price: 8.15,
    image: 'path',
  },
  {
    id: 13,
    idCategory: 1,
    name: 'Kitkat',
    description: 'Chocolate Kitkat Nestlé 41,5g',
    price: 3.45,
    image: 'path',
  },
  {
    id: 14,
    idCategory: 1,
    name: 'Snickers',
    description: 'Chocolate Snickers Original 52,7g',
    price: 3.25,
    image: 'path',
  },
  {
    id: 15,
    idCategory: 1,
    name: 'Laka Oreo',
    description: 'Chocolate Lacta Laka Oreo 20g',
    price: 2.5,
    image: 'path',
  },
  {
    id: 16,
    idCategory: 1,
    name: 'Laka Branco',
    description: 'Chocolate Lacta Laka Branco 20g',
    price: 2.5,
    image: 'path',
  },
  {
    id: 17,
    idCategory: 1,
    name: 'Diamante Negro',
    description: 'Chocolate Lacta Diamante Negro 20g',
    price: 2.5,
    image: 'path',
  },
  {
    id: 18,
    idCategory: 1,
    name: 'Lacta Ao Leite',
    description: 'Chocolate Lacta Ao Leite 20g',
    price: 2.5,
    image: 'path',
  },
  {
    id: 19,
    idCategory: 0,
    name: 'Água Com Gas',
    description: 'Água Crystal Com Gas 500ml',
    price: 3.85,
    image: 'path',
  },
  {
    id: 20,
    idCategory: 0,
    name: 'Água Mineral',
    description: 'Água Mineral Crystal Sem Gás 500ml',
    price: 3.85,
    image: 'path',
  },
  {
    id: 21,
    idCategory: 2,
    name: 'Cookie',
    description: 'Cookie Com Gotas De Chocolate 250g',
    price: 3.0,
    image: 'path',
  },
  {
    id: 22,
    idCategory: 2,
    name: 'Fatia de Bolo',
    description: 'Fatia de Bolo 450g',
    price: 6.55,
    image: 'path',
  },
  {
    id: 23,
    idCategory: 2,
    name: 'Salada',
    description: 'Prato de salada 200g',
    price: 9.0,
    image: 'path',
  },
  {
    id: 24,
    idCategory: 2,
    name: 'Hamburger',
    description: 'Hamburger 700g',
    price: 10.0,
    image: 'path',
  },
  {
    id: 25,
    idCategory: 2,
    name: 'Batata Frita',
    description: 'Batata frita 400g',
    price: 5.5,
    image: 'path',
  },
  {
    id: 26,
    idCategory: 3,
    name: 'Café Americano',
    description: 'Café Americano 200ml',
    price: 7.0,
    image: 'path',
  },
  {
    id: 27,
    idCategory: 3,
    name: 'Cappuccino',
    description: 'Cappuccino 200ml',
    price: 9.0,
    image: 'path',
  },
  {
    id: 28,
    idCategory: 3,
    name: 'Mocha',
    description: 'Mocha 200ml',
    price: 9.0,
    image: 'path',
  },
  {
    id: 29,
    idCategory: 3,
    name: 'Café Preto',
    description: 'Café Preto 200ml',
    price: 8.0,
    image: 'path',
  },
  {
    id: 30,
    idCategory: 3,
    name: 'Espresso',
    description: 'Espresso 200ml',
    price: 7.0,
    image: 'path',
  },
  {
    id: 31,
    idCategory: 3,
    name: 'Latte',
    description: 'Latte 200ml',
    price: 8.5,
    image: 'path',
  },
  {
    id: 32,
    idCategory: 3,
    name: 'Latte Com Creme',
    description: 'Latte Com Creme 200ml',
    price: 8.85,
    image: 'path',
  },
  {
    id: 33,
    idCategory: 0,
    name: 'Ice Latte',
    description: 'Ice Latte 200ml',
    price: 8.75,
    image: 'path',
  },
  {
    id: 34,
    idCategory: 0,
    name: 'Ice Coffee',
    description: 'Ice Coffee 200ml',
    price: 8.5,
    image: 'path',
  },
];

export default Products;
